# Generated by Django 6.0.6 on 2026-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='bio',
            name='slug',
            field=models.SlugField(default='abdul-wahab', help_text='URL-friendly identifier, e.g. abdul-wahab', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile photo (stored in media/bio/)', null=True, upload_to='bio/'),
        ),
    ]
