# Generated by Django 6.0.6 on 2026-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_bio_linkedin_bio_slug_alter_bio_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
    ]
