# Generated by Django 6.0.6 on 2026-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_bio_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='website',
            field=models.URLField(blank=True, help_text='Personal portfolio or website URL'),
        ),
    ]
